sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

install:
  - mvn package -Pfatjar
  - ./blackbox.sh verify

notifications:
  email:
    recipients:
      - jon.o.gille@gmail.com